pipeline{
   agent any 
   tools{
    maven 'M2_HOME'
   }
   stages{
     stage("SonarQube analysis") {          
            steps {
             withSonarQubeEnv('sonarq') {
            sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=tdh1961_geo-mai2024'

             }
            }
        }
    stage("maven"){
        steps{ 
        sh 'mvn clean '
        sh 'mvn validate'
        sh 'mvn compile' 
        sh 'mvn install' 
        sh 'mvn test'
        sh 'mvn package'
        }
    }
    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:AP2pVAGB8Lcqx4h8N6Rvrn75bDo -T \
            target/bio*.jar \
            "http://107.23.121.36:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'  
            
            }
    }
   }
  
}